### PR TITLE
Package SO: SO-4_4.4x3.9mm_P2.54mm scripetd version source

### PR DESCRIPTION
**Pull request by myfreescalewebpage**
Size definition from TLP3123, datasheet at https://toshiba.semicon-storage.com/info/docget.jsp?did=10047&prodName=TLP3123

PR on kicad footprint repo : https://github.com/KiCad/kicad-footprints/pull/1424

Joel

### CODE REVIEW

**Comment by poeschlr** [comment]
The datasheet uses nominal plus tolerance but you use min/max.
Please enter dimensions in the same style as in the datasheet.

Example:
```yaml
  body_size_x:
    nominal: 4.4
    tolerance: 0.25
```

**Comment by myfreescalewebpage** [comment]
@poeschlr fixed

**Comment by poeschlr** [comment]
All measurements are given as nominal plus tolerance in the datasheet so please make all yaml specs fit that style of dimensioning. (Doing math is error prone this is why the yaml style must fit the datasheet.)

**Comment by myfreescalewebpage** [comment]
oooops sorry for that, have made the previous fix too much quickly ! Should be correct now.

**Comment by evanshultz** [comment]
The YAML file is correct but there is a big comment which perhaps should be removed? I've mentioned the scripts in general need documentation, but putting this in the middle of one component entry is not the right place.

**Comment by myfreescalewebpage** [comment]
Done for this definition, probably this is something to cleanup every where if other are present, and written in a README file.

**Pull request merged**
