### PR TITLE
Fix footprints of RECOM DC/DC converters.

### PR DESCRIPTION
**Pull request by rschaeuble**
Some had their pins towards the front instead of towards the back, some had a wrong  pin 1 offset, and other had wrong widths.

Also refactored the script to put different families of controllers into different functions.

See https://github.com/KiCad/kicad-footprints/pull/688 for the original pull request which triggered this one.

### CODE REVIEW

**Comment by rschaeuble** [comment]
The footprint changes have been merged, so this one can now also be merged.

**Comment by rschaeuble** [comment]
@pointhi: as the footprints have already been merged, could you please merge this pull request?

**Comment by rschaeuble** [comment]
@pointhi Is there anything that still needs to be done before this can be merged?

As the footprints have already been merged, it would be great if the generator changes could be merged soon as well.

**Comment by pointhi** [comment]
@rschaeuble I will merge now. Thanks for your contribution

**Pull request merged**
