### PR TITLE
Track new device type "SSO", add new definition for "SSO-8-N7_6.4x9.78mm_P2.54mm"

### PR DESCRIPTION
**Pull request by yankee14**
I submitted a [kicad-symbols PR](https://github.com/KiCad/kicad-symbols/pull/2602) for a [7-pin solid state relay](https://b2b-api.panasonic.eu/file_stream/pids/fileversion/2787). It comes in DIP as well as SMD package types. In trying to find some already-existing footprints that would be appropriate to use, @cp-aquila helped me find `DIP-8-N7_W7.62mm`, which seems to be appropriate. They also helped me find `SSO-8_6.7x9.8mm_P2.54mm_Clearance8mm`, which has some similarities to what I need.

`kicad-symbols` PR: https://github.com/KiCad/kicad-symbols/pull/2602
`kicad-footprints` PR: https://github.com/KiCad/kicad-footprints/pull/2212
`kicad-footprint-generator` PR: https://github.com/pointhi/kicad-footprint-generator/pull/527

In terms of generating this footprint, the `device_type: SSO` seems to not exist yet. I created a new file at `size_definitions/sso.yaml` with the definitions for this part. The result does not quite look right:

SSO-8_9 78x6 4mm_P2

If this should be done a different way, please advise.

### CODE REVIEW

**Comment by yankee14** [comment]
I think it looks better:

SSO-8_6 4x9 78mm_P2

**Comment by evanshultz** [comment]
The naming should now be corrected if you use the `hidden_pins` key in the YAML file. This was added recently so please update your script and try it again. The nomenclature comes from IPC 7351 which you can see on page http://ohm.bu.edu/~pbohn/__Engineering_Reference/pcb_layout/pcbmatrix/IPC-7x51%20&%20PCBM%20Land%20Pattern%20Naming%20Convention.pdf, and existing footprints should be corrected.

**Comment by yankee14** [comment]
@evanshultz thanks!

**Comment by myfreescalewebpage** [comment]
Fp has been merged

**Pull request merged**
