### PR TITLE
Add non-polar radial THT caps

### PR DESCRIPTION
**Pull request by evanshultz**
Added entries for non-polar THT caps to existing scripts. Also some minor cleanup for footprint name, description, and keywords based on footprint type.

### CODE REVIEW

**Comment by evanshultz** [comment]
Footprints submitted at https://github.com/KiCad/kicad-footprints/pull/1019.

**Comment by evanshultz** [comment]
If anybody wants to make 3D models here is the output script (I have no idea about it so YMMV):
[CQ_params_C_Radial.py.txt](https://github.com/pointhi/kicad-footprint-generator/files/2482777/CQ_params_C_Radial.py.txt)

Remove the .txt file extension.

**Comment by evanshultz** [comment]
Footprints have been merged.

**Comment by pointhi** [comment]
thx

**Pull request merged**
