### PR TITLE
Add entries for 3 QFNs and a WLCSP

### PR DESCRIPTION
**Pull request by evanshultz**
A few footprints used in several PRs.

QFN16 and QFN24:
https://github.com/KiCad/kicad-symbols/pull/1064
http://www.cypress.com/file/46236/download
image

LFCSP:
https://github.com/KiCad/kicad-symbols/pull/1180
https://www.analog.com/media/en/technical-documentation/data-sheets/AD7682_7689.pdf
image

WLCSP:
https://github.com/KiCad/kicad-symbols/pull/1189#issuecomment-443025084
http://ww1.microchip.com/downloads/en/devicedoc/atmel-8235-8-bit-avr-microcontroller-attiny20_datasheet.pdf#page=208
image

This PR relies on an update to bga.py which I'll submit soon.

### CODE REVIEW

**Comment by evanshultz** [comment]
The required script update for this to work is at https://github.com/pointhi/kicad-footprint-generator/pull/247.

**Comment by evanshultz** [comment]
@poeschlr 
Thanks. I left alone the lead pitch but I believe I did everything else above.

**Comment by evanshultz** [comment]
@poeschlr 
I think I'll have to create a new PR based on how GH is confused, but perhaps you could check this first?

**Comment by evanshultz** [comment]
@poeschlr 
Would you mind sucking these into your big QFN update adventure? I can then leave this PR to handle just the script update for the WLCSP (or create a new PR if that's what's best).

**Comment by evanshultz** [comment]
Merged in master and then re-implemented my QFN-2x changes in the new split up definition files. Removed the QFN-16 since a matching definition was added in the interim.

**Comment by pointhi** [comment]
@evanshultz does that mean the footprints are merged now?

**Comment by pointhi** [comment]
thx

**Pull request merged**
