### PR TITLE
Add a Harwing M20-89xx generator

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
Footprint PR:
https://github.com/KiCad/kicad-footprints/pull/368

### CODE REVIEW

**Comment by antoniovazquezblanco** [comment]
PR now in https://github.com/KiCad/kicad-footprints/pull/428

**Comment by antoniovazquezblanco** [comment]
Merged in KiCad footprint libraries.

**Comment by antoniovazquezblanco** [comment]
Ping @pointhi :)

**Comment by pointhi** [comment]
Thanks

**Comment by antoniovazquezblanco** [comment]
Thank you

**Pull request merged**
