### PR TITLE
Add TPS703xx PWP entry

### PR DESCRIPTION
**Pull request by evanshultz**
From http://www.ti.com/lit/ds/symlink/tps703.pdf. Footprints submitted at https://github.com/KiCad/kicad-footprints/pull/995.

### CODE REVIEW

**Comment by evanshultz** [comment]
Footprints have been merged.

**Comment by evanshultz** [comment]
Corrected footprints have not been merged.

**Comment by evanshultz** [comment]
https://github.com/KiCad/kicad-footprints/pull/1017

**Comment by pointhi** [comment]
please fix merge conflict

**Comment by evanshultz** [comment]
@pointhi @poeschlr 
I think I'm screwed. Any ideas how to fix this?

Because of another merge mine is broken and GH doesn't seem to understand how to handle changes in a simple text file. I've tried putting my commit before and after the section that was merged to the file but to no avail.

**Comment by evanshultz** [comment]
This is just hosed so I've replaced it with #217 .

**Pull request closed without merging**
