### PR TITLE
modify wrong spacings in Choke_Schaffner_RNXXX.py

### PR DESCRIPTION
**Pull request by Flo3561**
corrected description wrong manufacturer name
changed 3d model path
mechanical corrections for RN142,RN143,RN202,RN232 
added RN218

### CODE REVIEW

**Comment by Flo3561** [comment]
@pointhi I was wondering how the process regarding pull requests is working in this repo? Is it necessary to inform the maintainer group?

**Comment by pointhi** [comment]
@Flo3561 typically, the PR will be merged when the contribution was accepted in the KiCad repository

**Comment by Flo3561** [comment]
> @Flo3561 typically, the PR will be merged when the contribution was accepted in the KiCad repository

Okay, good to know. So I hope we will soon move forward on this side https://github.com/KiCad/kicad-footprints/pull/2079

**Comment by evanshultz** [comment]
@Flo3561 
RN232 looks like dimension H is 34.3 and so was correct before. Can you please check that? I grabbed the datasheet from the website so hopefully I have the latest info.

**Comment by Flo3561** [comment]
@evanshultz: This is actually a confusing point for me as well. On page 4 of the datasheet (second last column) the height for RN232 is mentioned with 29.3.
image
On page 8 another dimension (34.3) is mentioned in the table:
image

I asked Schaffner by email to clarify/correct on this point.

**Comment by Flo3561** [comment]
@evanshultz: Schaffner corrected their mistake in the datasheet. Correct height for RN232 is 34.3 mm.

**Comment by evanshultz** [comment]
Footprint PR: https://github.com/KiCad/kicad-footprints/pull/2107

You will need to re-generate footprints with the fix above. Or at least the impacted footprint. And resolve the branch conflict on the footprint PR. Then I think this is good. Thanks!

**Comment by Flo3561** [comment]
@evanshultz: I'm not sure if I have done it right...

**Comment by evanshultz** [comment]
Footprints are merged. Thank you!

**Pull request merged**
