### PR TITLE
Added Converter_DCDC_Murata_NCS1SxxxxSC_THT

### PR DESCRIPTION
**Pull request by Misca1234**
Scripts for creating DCDC converters based on standardbox.py

Data sheet
https://power.murata.com/data/power/ncl/kdc_ncs1.pdf

FP push
https://github.com/KiCad/kicad-footprints/pull/1044

See yml file for dimensions

bild

### CODE REVIEW

**Comment by Misca1234** [comment]
Increased the pin marker to 1.0 and rounded the pads around pin 2 and onward.

This push also contain a fix for standardbox.py where the pin 1 marker is at least 1.0 long and all line coordinates are rounded to 2 decimals

**Comment by tolot27** [comment]
> This push also contain a fix for standardbox.py where the pin 1 marker is at least 1.0 long and all line coordinates are rounded to 2 decimals

I do not see any changes to `standardbox.py` in the commits ...

**Comment by Misca1234** [comment]
Sorry, here they are

**Comment by pointhi** [comment]
thanks for your contribution

**Pull request merged**
