### PR TITLE
Added Stackpole serie of Ultra Precision Current Sensing Chip Resistor

### PR DESCRIPTION
**Pull request by Misca1234**
This is the serie of stackpole's Ultra Precision Current Sensing Chip Resistor 
https://www.seielect.com/catalog/SEI-CSS_cssh.PDF

They are all script generated with 
general/smd_chip.py 
with data in
smd_chip_resistors_smd.csv

Foot print push
https://github.com/KiCad/kicad-footprints/pull/737

Script push
https://github.com/pointhi/kicad-footprint-generator/pull/146

### CODE REVIEW

**Comment by poeschlr** [comment]
This script is obsolete. (see the text file in the same folder) It is replaced by https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/SMD_chip_package_rlc-etc

This is the reason why it does not really fulfill KLC (example off grid courtyard)

**Comment by Misca1234** [comment]
I guess I should update the smd_chip_resistors_smd.csv in Resistors_SMD and add entries like 
R_Stackpole_CSS0603 then ?

**Comment by poeschlr** [comment]
Sorry for the late response. The current generator uses yaml files not csv files. It also generates ipc compliant footprints but offers the interface to generate handsolder versions (increased toe fillet).

**Comment by Misca1234** [comment]
Ok, I will switch generator

**Pull request closed without merging**
