### PR TITLE
Adding Lattice_caBGA-756_27.0x27.0mm_Layout32x32_P0.8mm

### PR DESCRIPTION
**Pull request by ki5libs**
Adding Lattice_caBGA-756_27.0x27.0mm_Layout32x32_P0.8mm
[Datasheet](http://www.latticesemi.com/view_document?document_id=213) page 115

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@ki5libs can you solve the branch conflict here please ?
Then ready to be merged, the footprint has been merged.

**Comment by ki5libs** [comment]
Hi @myfreescalewebpage 

it seems to be working now.

**Comment by myfreescalewebpage** [comment]
I'm not sure, why removing "bga.py" ?

**Comment by ki5libs** [comment]
"bga.py" does not exist anymore. Looks like it was renamed to "ipc_bga_generator.py" and then changed in master branch. I don't know why it was part of this commit because I've actually changed "bga.yaml" only.

**Comment by myfreescalewebpage** [comment]
ok, strange that the git diff shows this deletion on your pull request, but I agree it is not on master.
@poeschlr @chschlue this PR can be merged now, fp is merged

**Pull request merged**
