### PR TITLE
BGA script update

### PR DESCRIPTION
**Pull request by evanshultz**
This update is required for https://github.com/pointhi/kicad-footprint-generator/pull/246.

My objective was to support unique X and Y pitches, but I went further. There are two commits:
1. Adding the basic functionality I needed.
1. Performing commonalization with the other Package_ scripts by Rene to a large extent.

Broken down by feature changes, the changes are:
- Support unique X and Y pitch
- Stream in YAML input files
- Use common global config files
- Build configurable and bigger list of row names

The last item above includes https://github.com/pointhi/kicad-footprint-generator/pull/238 and one commit of https://github.com/pointhi/kicad-footprint-generator/pull/208 (specifically https://github.com/pointhi/kicad-footprint-generator/pull/208/commits/2cd8f9ac0d43d2be3c31cb6e7f37fdc27b64e0e1) and one commit of https://github.com/pointhi/kicad-footprint-generator/pull/240 (specifically https://github.com/pointhi/kicad-footprint-generator/pull/240/commits/4bbbeed238ca87483c777ba387ddf7ae8871bb57), but it does it in a programmatic way that is easier to maintain. This could be split out into a separate helper function, but I didn't see that it applied to other footprints types so I kept it in the existing `bga.py` script.

There are a few remaining things that could further align the Package_* scripts, which are not done here. In somes cases this is simply because of outstanding PRs, in other cases I figured we should talk about it first (and it might be blocked by a PR anyway). Any of the below items should wait for a future PR.
1. Push this folder down a level to the Package folder.
1. Rename the external data files from YML to YAML extension.
1. Use a series configuration file. (IMO it's OK as it is but it could be more flexible.)
1. Allow ball size to be entered and derive padstack design from IPC rules.

### CODE REVIEW

**Comment by evanshultz** [comment]
@Ratfink 
I know you're busy, but since you originated this script I'd be happy to hear any comments.

@poeschlr 
This was the only Package_* script not written by you. Is this an acceptable alignment to what I would expect is now our in-house "standard"? Is there something you'd like done if we're going to update this script to support external config files and stream YAML input data?

**Comment by tpambor** [comment]
Sorry for the inconvenience I expected it to be kept open until this one landed. You should be able to resolve the conflict by merging master into your branch and resolve the conflict by keeping your version.

**Comment by evanshultz** [comment]
@pointhi 
Should be good now. Sorry that I was a bit naive in resolving this, so you may want to squash merge.

**Comment by pointhi** [comment]
@poeschlr can I merge this?

**Pull request merged**
