### PR TITLE
Molex 90814 2

### PR DESCRIPTION
**Pull request by Misca1234**
A push for the Molex Picoflex serie 90814, it is related to push

https://github.com/KiCad/Connectors_Molex.pretty/pull/49

### CODE REVIEW

**Comment by Misca1234** [comment]
Dont merge this before push 
https://github.com/KiCad/Connectors_Molex.pretty/pull/49

is merged

**Comment by Misca1234** [comment]
Changed in the kicad build script the model attributes
at, scale and rotation from [0,0], [0,0,0], [0,0,0] to [0,0,0], [1,1,1] and [0,0,0]

**Comment by pointhi** [comment]
can you please rebase this PR to only handle your changes

**Comment by Misca1234** [comment]
This push have been replaced by 
https://github.com/pointhi/kicad-footprint-generator/pull/59

**Pull request closed without merging**
