### PR TITLE
Add Inductors/Murata_DEM35xxC

### PR DESCRIPTION
**Pull request by asukiaaa**
Related PR: https://github.com/KiCad/kicad-footprints/pull/1109

### CODE REVIEW

**Comment by asukiaaa** [comment]
The symbol created with using this script has been merged.
https://github.com/KiCad/kicad-footprints/pull/1109

**Comment by asukiaaa** [comment]
I wanted to just add a comment but I accidentally closed.
If you have motivation to merge this pull request, please reopen it and merge.
Thank you.

**Comment by asukiaaa** [comment]
Thank you for opening  this PR.
If you give me some feedback, I will handle them.

**Comment by pointhi** [comment]
should be fine

**Comment by asukiaaa** [comment]
Thank you for merging.

**Pull request merged**
