### PR TITLE
BGA script update

### PR DESCRIPTION
**Pull request by evanshultz**
Here is an incremental improvement to the BGA script:
1. Moved one level down with the other Package_* scripts
1. Extract information from the parameters to build the footprint name, description, etc. instead of pulling this in from a manually-entered string for each footprint
1. Renamed variables to conform with existing Package_* scripts and allow the package height to be included so the same YAML file could potentially support 3D model generation
1. Renamed internal variables for consistency

This resulted in the following changes to the YAML files:
1. Changed their file extension to YAML
1. Variable renames
1. Moving doc link to a separate variable
1. Removing duplicated info from the description string
1. Removed "_NSMD" from footprint names since this is the library default

I also included the (currently unused) IPC 7351B BGA ball size info, which could be implemented to find the land pattern size from the ball size if the land pattern isn't provided or if IPC-compliance is desired.

### CODE REVIEW

**Comment by evanshultz** [comment]
@Ratfink 
@poeschlr 
@herostrat 
Do any of you want to review and chime in on this?

**Comment by herostrat** [comment]
> Here is an incremental improvement to the BGA script:
> 
>     1. Moved one level down with the other Package_* scripts

I agree that the position is better suited.

>     2. Extract information from the parameters to build the footprint name, description, etc. instead of pulling this in from a manually-entered string for each footprint

We talked about this in my first PR, I love this change.

>     3. Renamed variables to conform with existing Package_* scripts and allow the package height to be included so the same YAML file could potentially support 3D model generation

X and Y as dimensions are much better as height is imho the z-axis.
So I also agree with this change.

> This resulted in the following changes to the YAML files:
> 
>     1. Changed their file extension to YAML
> 
>     2. Variable renames
> 
>     3. Moving doc link to a separate variable
> 
>     4. Removing duplicated info from the description string
> 
>     5. Removed "_NSMD" from footprint names since this is the library default

I have verified that the Xilinx footprints are correct, the order of information in the description changed a bit, but is still understandable and logical.

**Comment by evanshultz** [comment]
@poeschlr 
I know you've been busy lately, but could you give this a thumbs up or suggest changes? Since all the files are changed and moved it would be nice to get this merged quickly so that new contributions can base off of this and not create a mess. Thanks!

**Comment by evanshultz** [comment]
@poeschlr 
https://github.com/KiCad/kicad-footprints/pull/1604 is the first new PR since I submitted this which could use the BGA script. Would you be able to approve this or make suggestions so it can get merged?

**Comment by evanshultz** [comment]
@poeschlr 
Can you please take a look at this?

@pointhi 
Usually Rene has good input and seems like a logical approver, but that can be a bottleneck. What are your requirements to merge contributions that don't touch the KicadModTree framework like this? The head librarian must approve? Will a thumbs up by any librarian work? Something else?

**Comment by pointhi** [comment]
@evanshultz I'm fine as long as PR do not touch the KicadModTree framework. I think it would be a good idea to give @poeschlr merge priviledges on this repo :)

**Comment by evanshultz** [comment]
@pointhi 
Agreed. Having other people that can merge to this repo would be nice.

So then, as I'm not touching the framework, are you willing to merge this PR?

**Pull request merged**
