### PR TITLE
Add LQFP-52_14x14mm_P1mm size definition

### PR DESCRIPTION
**Pull request by diegoherranz**
To be used with https://github.com/KiCad/kicad-symbols/pull/1193
Footprint submitted in https://github.com/KiCad/kicad-footprints/pull/1123

Thanks!

### CODE REVIEW

**Comment by poeschlr** [comment]
The footprint has been merged. Meaning this can be merged now.

**Comment by poeschlr** [comment]
I merged your pull request into mine. (reduces workload for @pointhi)

Thanks for your work.

**Comment by diegoherranz** [comment]
And then @pointhi pulls from your fork?
What should I do with this PR? Leave it open until that happens?

Thanks.

**Comment by diegoherranz** [comment]
OK, I had misunderstood. I somehow thought you had added it to your fork of this repo and I couldn't understand the flow. It makes sense now :)

Thanks!

**Pull request closed without merging**
