### PR TITLE
Lfcsp 16 1 ep 3 x3mm p0.5mm ep1.7x1.7mm new

### PR DESCRIPTION
**Pull request by matthuszagh**
https://www.analog.com/media/en/technical-documentation/data-sheets/HMC7992.pdf

### CODE REVIEW

**Comment by poeschlr** [comment]
Is it on purpose that this includes two contributions?

**Comment by matthuszagh** [comment]
No, it isn't. Sorry about that. It should be fixed now.

**Comment by poeschlr** [comment]
You will also need to manually merge the current master into this branch as there is a merge conflict right now.

**Comment by poeschlr** [comment]
@pointhi the footprint is merged this one is good to go once the merge conflict is resolved.

**Comment by poeschlr** [comment]
thanks

**Pull request merged**
