### PR TITLE
Added molex MicroFit 3.0 43045 serie XX10 and XX11

### PR DESCRIPTION
**Pull request by Misca1234**
This is the script push for 
https://github.com/KiCad/Connectors_Molex.pretty/pull/51

### CODE REVIEW

**Comment by Misca1234** [comment]
Changed in the kicad build script the model attributes
at, scale and rotation from [0,0], [0,0,0], [0,0,0] to [0,0,0], [1,1,1] and [0,0,0]

**Comment by Misca1234** [comment]
New update, librarians wanted to shorten pin 1 in F.Silk layer

**Comment by Misca1234** [comment]
Push 
https://github.com/KiCad/Connectors_Molex.pretty/pull/51

have been merged, this can be merged as well

**Comment by pointhi** [comment]
thanks

**Pull request merged**
