### PR TITLE
Add further qfn dimensions

### PR DESCRIPTION
**Pull request by poeschlr**

### CODE REVIEW

**Comment by evanshultz** [comment]
@poeschlr 
Could you add a guide showing all parameters of the script, which ones are used together, which ones are optional, etc.? Perhaps also a link to an example package drawing for each set of arguments as a reference for how the information should be parsed and provided as a script input? I realize reading through the various YAML files can help here, but your framework is so powerful that a user guide would be helpful in order to broaden the audience of this tool.

**Comment by poeschlr** [comment]
Right now i am mainly working on consolidating the various generators. My end goal is to have one generator for all possible ic packages. once i reach that goal we can think about documentation (until then reading yaml files of similar components should be enough information for everyone who is in a hurry.)

My real end goal is to have the ipc generators as a footprint wizard. But that will have to wait till the footprint wizard works again under linux as i am not prepared to work under windows.

**Comment by evanshultz** [comment]
Note that there are footprint PRs using entries for this generator at https://github.com/KiCad/kicad-footprints/pull/852#issuecomment-414857666 and https://github.com/KiCad/kicad-footprints/issues/851#issuecomment-414472929.

**Comment by evanshultz** [comment]
I'm still being annoying about this PR. It's really over grown into a monster.

In addition to the above items, a couple more things:
- `drawing_tools.py` has a function named `nearestSilkPointOnOrtoLine`. "To" is missing a capital "T".
- The parameter information in `KicadModTree/nodes/base/Pad.py` has two typos for `maximum_radius`: "usefull" needs one less "l" and typo of "compliance".

Can these last things be done and this get merged?

**Comment by poeschlr** [comment]
@evanshultz 
The reason this is a monster is quite simple: Two very large pull requests connected to this one where not merged into the footprint repo for a very long time. (Nobody reviewed them)

Now your comments:
> drawing_tools.py has a function named nearestSilkPointOnOrtoLine. "To" is missing a capital "T".

Orto is the short version of orthogonal so it is not missing a capital t but a h. (I choose to write out orthogonal)


> The parameter information in KicadModTree/nodes/base/Pad.py has two typos for maximum_radius: "usefull" needs one less "l" and typo of "compliance".

fixed

---

Added your SSOP to a new size definition file.
I also added the one parameter set of your merged pull request. I did not (yet) add the other one as i do not want to stall this further.

**Comment by poeschlr** [comment]
@pointhi all footprints connected to this have been merged

**Comment by poeschlr** [comment]
@pointhi fixed the travis errors

**Comment by pointhi** [comment]
@poeschlr,

thanks. Looks fine now

**Comment by pointhi** [comment]
@poeschlr I will merge now

**Pull request merged**
