### PR TITLE
LQFP-64 with 5mmx5mm EP

### PR DESCRIPTION
**Pull request by twam**
Footprint for https://github.com/KiCad/kicad-symbols/pull/1594

### CODE REVIEW

**Comment by poeschlr** [comment]
The datasheet defines min and max values in addition to the nominal values. These must be included to get the correct footprint. (The tolerance is part of the pad calculation)

**Comment by twam** [comment]
I added minimum/maximum values were given in the datasheet.

**Comment by poeschlr** [comment]
You will need to update the footprint over on the footprint repo as well. (adding tolerance info will result in a different footprint. This is why it is required to be entered.)

**Comment by twam** [comment]
Wanted to update this, after this was merged to avoid to many activity there. However rerun the script and updated https://github.com/KiCad/kicad-footprints/pull/1461.

**Comment by poeschlr** [comment]
thanks

**Pull request merged**
