### PR TITLE
add definition for LFCSP-8 3x3mm from Analog

### PR DESCRIPTION
**Pull request by lorem-ipsum**
Add a yaml definition for a LFCSP chip from Analog Devices to the DFN_QFN package generator. [Package documentation](https://www.analog.com/media/en/package-pcb-resources/package/pkg_pdf/lfcspcp/cp-8/CP_8_13.pdf)

### CODE REVIEW

**Comment by poeschlr** [comment]
The footprint has been merged. This is good to go.

**Comment by lorem-ipsum** [comment]
an issue which I forgot to mention is that the footprint is placed in Package_DFN_QFN at generation, but should go into Package_CSP. If one does the move manually this is not an issue, but it might generate problems for scripts later on.

**Comment by poeschlr** [comment]
Regarding your last comment: There is the library parameter that can be used to fix this. (I added this to your script such that i can merge it.)

**Comment by evanshultz** [comment]
@lorem-ipsum 
@poeschlr 
The YAML file is now in an abandoned directory. Would one of you be willing to move it to the correct place and delete the unused directory in a new PR, please?

**Pull request merged**
