### PR TITLE
Adding qfn footprint size definitions

### PR DESCRIPTION
**Pull request by poeschlr**
This pull request will eventually add some of the missing qfn footprints that are currently in the lib.

Additionally i convert over the size definition files to the new style and also include the package height for eventual use in the 3d generator.

### CODE REVIEW

**Comment by evanshultz** [comment]
All footprints are merged.

**Comment by poeschlr** [comment]
I am not finished here. Will give notice as soon this is done.

**Comment by poeschlr** [comment]
@pointhi i am done for now with this. All footprints have been merged.
(There will for sure be future additions but lets not let master fall behind to far.)

**Comment by pointhi** [comment]
@poeschlr thanks for your great addition

**Pull request merged**
