### PR TITLE
Wdfn-8_1ep_6x5mm

### PR DESCRIPTION
**Pull request by serkanxselcuk**
Datasheet: http://ww1.microchip.com/downloads/en/DeviceDoc/8L_WDFN_5x6mm_MF_C04210B.pdf
image

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@serkanxselcuk please remove empty lines and comment lines which are not useful

**Comment by serkanxselcuk** [comment]
Done

**Comment by myfreescalewebpage** [comment]
No more comment.

**Comment by myfreescalewebpage** [comment]
Footprint has been merged

**Comment by cpresser** [comment]
@myfreescalewebpage did you review this one? Should I merge it?

**Comment by myfreescalewebpage** [comment]
Yes you can

**Pull request merged**
