### PR TITLE
Add MSOP-8_3x3mm_P0.65mm

### PR DESCRIPTION
**Pull request by chschlue**
https://github.com/KiCad/kicad-footprints/pull/1901

https://www.jedec.org/system/files/docs/mo-187F.pdf

### CODE REVIEW

**Comment by evanshultz** [comment]
1. Please update `size_source` to capture that this is `MO-187AA`. There are other variantions.
1. There is tolerance for the body size in the JEDEC doc: both width and height are +/-0.2mm (`aaa`).
1. Similarly, overall size tolerance is +/-0.25mm.
1. Can you include package height?

**Comment by chschlue** [comment]
1. I know, but size_source is supposedly of {url} type. What am I supposed to do, add a pseudo page anchor?

**Comment by evanshultz** [comment]
We did this on some other part that Rene added. I think he just overloaded the string since there was no validation. That probably works here since I don't believe a dedicated field for info has been added yet.

**Comment by chschlue** [comment]
Done.

**Comment by evanshultz** [comment]
Thanks! This doesn't have an EP so it's OK to do.

**Pull request merged**
