### PR TITLE
Add APDS DFN6 footprint from broadcom

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
See https://github.com/KiCad/kicad-footprints/pull/1196

### CODE REVIEW

**Comment by poeschlr** [comment]
I noticed body height is not quite the right name for giving the height. I changed it to overall_height in my open pull requests

**Comment by antoniovazquezblanco** [comment]
Will change that. Maybe your PRs should be merged before and then I will update mine.

Thank you!

**Comment by poeschlr** [comment]
Yours does not clash with mine. (I do not touch any DFN size definition files)

**Comment by antoniovazquezblanco** [comment]
Sorry. I messed up. Reopening at https://github.com/pointhi/kicad-footprint-generator/pull/293

**Pull request closed without merging**
