### PR TITLE
Point grid

### PR DESCRIPTION
**Pull request by SchrodingersGat**
One of requirements for the courtyard is that it falls on an 0.05mm grid. I've added a "grid=" keyword (optional) to point/line/polygoneline/rectline to force the points of the lines to fall on the grid.

### CODE REVIEW

**Comment by pointhi** [comment]
I also had similar ideas, but I think I do the implementation by myself.

Those functionality could be implemented in a simpler, and much more flexible way.

**Comment by SchrodingersGat** [comment]
Did you ever implement the "grid" functionality - if so, where in the code is it implemented? I would like to transfer my scripts to using *your* grid implementation if it exists :)

**Comment by pointhi** [comment]
Please rebase to the current master and remove those parts with default line width & co.

I do not longer know what idea I had before, and after rereading over this proposal it seems like a good way to implement this feature.

**Comment by pointhi** [comment]
Furthermore, this code should be moved into the render method, otherwise there could be rounding errors.

**Comment by SchrodingersGat** [comment]
I have fixed conflicts!

I have left the grid code where it is - I tried putting it in the render method but it was not getting called! I think somewhere a new Point object is being made and the grid data is lost...

**Comment by SchrodingersGat** [comment]
Fixed conflicts with master branch

**Comment by pointhi** [comment]
@SchrodingersGat
I added a ```round_to``` method to the Point class to support such things like aligning to a grid (as long as no transformations are applied). Is this Pull Request still of relevance?

https://kicad-footprint-generator.readthedocs.io/en/latest/KicadModTree.html#KicadModTree.Point.Point2D.round_to

**Comment by SchrodingersGat** [comment]
That sounds sufficient, thanks :)

**Pull request closed without merging**
