### PR TITLE
add RECOM SIP-packages

### PR DESCRIPTION
**Pull request by jkriege2**
used here: https://www.recom-power.com/pdf/Innoline/R-78Exx-0.5.pdf
2017-10-21 17_57_56-footprint editor no active library
2017-10-21 17_57_45-footprint editor no active library
2017-10-21 15_13_23-footprint editor no active library

### CODE REVIEW

**Comment by pointhi** [comment]
please could you not reformat existing scripts with tabs

**Comment by jkriege2** [comment]
fixed those reformats

**Comment by jkriege2** [comment]
woops I though i had changed all of them back ... so I changed all that I could find from tab back to whitespaces and fixed the conflicts.

Hope that's OK like this now!

JAN

**Comment by pointhi** [comment]
thanks

**Pull request merged**
