### PR TITLE
Add SOIC-8 5.23x5.23mm.

### PR DESCRIPTION
**Pull request by matthuszagh**
Add 5.23x5.23 version

### CODE REVIEW

**Comment by pointhi** [comment]
please link kicad pull request

**Comment by matthuszagh** [comment]
footprint pr: https://github.com/KiCad/kicad-footprints/pull/1486

**Comment by poeschlr** [comment]
@pointhi the footprint has been merged this is good to go.

**Comment by poeschlr** [comment]
Thanks

**Pull request merged**
