### PR TITLE
Added DFN-8-1EP_2x2mm_P0.5mm_EP0.7x1.3mm

### PR DESCRIPTION
**Pull request by cnieves1**
Datasheet: https://www.onsemi.com/pub/Collateral/NUF4401MN-D.PDF

### CODE REVIEW

**Comment by chschlue** [comment]
#422

**Comment by cnieves1** [comment]
Could you please tell me what exact changes are required by https://github.com/pointhi/kicad-footprint-generator/pull/422 ?

As I understand, it is a change in the script. 
Do I need to change any data introduced in this PR?

Thanks,

**Comment by chschlue** [comment]
You don't generally need to change any FP data.
The important part is generating the FPs based on https://github.com/pointhi/kicad-footprint-generator/commit/37899c95f6510d711de9bc869ca144f0efaa4cc2, i.e. pulling current master into your branch before regenerating.

**Comment by cnieves1** [comment]
Ok. Regenerated footprint updated at:
https://github.com/KiCad/kicad-footprints/pull/2004

**Comment by chschlue** [comment]
FP merged.

**Pull request merged**
