### PR TITLE
Add 6x6mm UQFN-48

### PR DESCRIPTION
**Pull request by fauxpark**
This footprint is required by https://github.com/KiCad/kicad-symbols/pull/1189
No link to package drawing, but there is a picture here: https://github.com/KiCad/kicad-symbols/pull/1189#issuecomment-449506354

tv

### CODE REVIEW

**Comment by evanshultz** [comment]
Please update the script with tolerancing, as Rene caught on my initial commit at https://github.com/pointhi/kicad-footprint-generator/pull/246.

**Comment by fauxpark** [comment]
@evanshultz how is this?

**Comment by evanshultz** [comment]
The lead width looks incorrect.

But I believe Rene was asking to use the dimensions exactly as written in the datasheet for easiest matching. That would be:
```
  body_size_x:
    minimum: 5.9
    nominal: 6
    maximum: 6.1
  body_size_y:
    minimum: 5.9
    nominal: 6
    maximum: 6.1
  lead_width:
    minimum: 0.15
    nominal: 0.2
    maximum: 0.25
  lead_len:
    minimum: 0.3
    nominal: 0.4
    maximum: 0.5
```

The script sucks in dimensions in a variety of formats for this reason, but it does mean that another entry in the YAML file may be a poor reference if the drawings are dimensioned differently.

Too bad we don't have a released drawing. :(

**Comment by evanshultz** [comment]
@pointhi 
This footprint is merged, however, before you merge would you ping @fauxpark and I? If the official package drawing is released by Microchip we can update that in the script before merging this.

**Comment by evanshultz** [comment]
The package drawing hasn't been posted to https://www.microchip.com/quality/packaging-specifications?packageFamily=UQFN as of 29 Dec. Go ahead and merge if you like.

**Comment by pointhi** [comment]
thx. If something changes just create a new PR :)

**Pull request merged**
