### PR TITLE
Adding missing TI footpritns to size definition files

### PR DESCRIPTION
**Pull request by poeschlr**
Work in progress. This will in the end add ti footprints that are currently in the library to the script.

### CODE REVIEW

**Comment by evanshultz** [comment]
1. Texas_S-PVQFN-N24_EP is missing body height.
1. Texas_S-PVQFN-N36_EP starts at page 31, not 32.
1. Texas_S-PVQFN-N40_EP4.15x4.15mm should link to page 70.
1. Texas_S-PVQFN-N40_EP4.6x4.6mm isn't in the datasheet used. Which one did you select?

Screenshots in the footprint PR or here are helpful, but I just validated the input data and that was worked fine in the past.

**Comment by poeschlr** [comment]
I mainly add screenshots for a sanity check ;) (mainly for seeing the resulting paste layout especially in combination with vias.)

**Comment by poeschlr** [comment]
All datasheet links have been fixed

**Comment by poeschlr** [comment]
@pointhi all footprints generated by this have been merged. Meaning this should be good to go.

**Pull request merged**
