### PR TITLE
Add Texas RGE0024C definition

### PR DESCRIPTION
**Pull request by chemicstry**
Based on the RGE0024H, but smaller EP

http://www.ti.com/lit/ds/symlink/pca9548a.pdf#page=31

### CODE REVIEW

**Comment by poeschlr** [comment]
Could you please use the newer style of defining dimensions:

```yaml
dimension_name:
  minimum: xx.x
  nominal: xx.x
  maximum: xx.x
  tolerance: xx.x # or [-xx.x, xx.x] for asymmetrical tolerances
```

use the same style as in the datasheet. If the datsheet uses nominal plus tolerance then use nominal plus tolerance. If it uses minimum, maximum and nominal then use the same. (If only min/max is given then leave out the nominal dimension.)

The only dimension that does not use this style is the pin pitch. (assumed to be given as a reference value with 0 tolerance.)

If a dimension is given as reference then use nominal plus tolerance with tolerance set to 0.

Could you also include what is given of the overall height (I suggest right after body_size_y)?
```yaml
overall_height:
  maximum: 1
```

You can remove the ep size limit parameters. (They are no longer required)

EP paste coverage of 80% seems excessive. It is right at the maximum suggested value i ever read in any document.
I typically use 65% for parts with no vias or where vias are avoided by paste and 70% where paste overlaps vias.

Note: I did not check any parameters in detail. (Do not really have time for that right now.)

**Comment by chemicstry** [comment]
Updated as requested. I assume via drill size does not use that format?

80% EP paste coverage was given in the datasheet, should I reduce it to 70% anyway?

**Comment by DanSGiesbrecht** [comment]
@poeschlr @pointhi, do these changes look good?

**Comment by evanshultz** [comment]
@chemicstry 
Just two things to do:
1. Use 65% paste coverage. Our library is general purpose so using our standard values will be correct.
1. The datasheet page is 34, not 31.

**Comment by chemicstry** [comment]
@evanshultz 
Fixed as requested. Should I update the [PR](https://github.com/KiCad/kicad-footprints/pull/1395) over at the kicad-footprints repo too? Or do these scripts get generated in an automated way?

**Comment by evanshultz** [comment]
Looks good. Please update the footprint at https://github.com/KiCad/kicad-footprints/pull/1395 and then we can move back to the symbol. :)

**Comment by evanshultz** [comment]
Hehe. Cross-posting. Yes, please.

**Comment by evanshultz** [comment]
@pointhi 
Footprint has been merged.

**Comment by evanshultz** [comment]
@pointhi 
Footprint has been merged.

**Comment by evanshultz** [comment]
@pointhi 
Footprint has been merged.

**Comment by poeschlr** [comment]
Thanks

**Pull request merged**
