### PR TITLE
Rework generator script for smd single row connectors (JST and Molex)

### PR DESCRIPTION
**Pull request by poeschlr**
I replaced a few generators with a single more generic generator.

The footprints will be added to the kicad-footprint repo. (I will inform you when it is ready to be merged. I need this PR for cross referencing it in my other pull requests.)

### CODE REVIEW

**Comment by poeschlr** [comment]
@pointhi The footprints have been merged. The cleanup or the remaining scripts will happen later.

**Comment by poeschlr** [comment]
@pointhi I will do the cleanup of the remaining jst scripts also in this PR so do not merge. (Otherwise i would need to merge later on.)

**Comment by poeschlr** [comment]
@pointhi This is now ready to merge.
All the footprints generated with these scripts are merged into the new kicad-footprints repo.

**Comment by pointhi** [comment]
Thanks. That a quite big pull request.

**Pull request merged**
